blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/username/docker-compose-selector/discussions/new?category=ideas
    about: Suggest an idea for this project
  - name: Ask a Question
    url: https://github.com/username/docker-compose-selector/discussions/new?category=q-a
    about: Ask the community for help
  - name: Report a Bug
    url: https://github.com/username/docker-compose-selector/issues/new?template=bug_report.md
    about: Create a report to help us improve 