blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/ajnart/docker-compose-maker/discussions/new?category=feature-suggestion
    about: Suggest an idea for this project
  - name: Ask a Question
    url: https://github.com/ajnart/docker-compose-maker/discussions/new?category=q-a
    about: Ask the community for help 